---
- aur:
    use: yay
    state: present
    name:
      # - kafka
      - kaf

- name: Install confluent cli
  shell: curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b /usr/local/bin v2.3.1
  become: yes