---
# - name: Create AUR user
#   user:
#       name: aur_builder
#       create_home: no
#       group: wheel
- name: Disabled password for pacman
  lineinfile:
    path: /etc/sudoers.d/11-install-wcarlsen
    line: 'wcarlsen ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: yes
