---
- name: Create kube folder
  file:
    path: ~/.kube
    state: directory

- name: Install Kuberentes tooling
  pacman:
    state: present
    name:
      - k9s
      - kubectl
      - kubectx
      - minikube
      - helm
      - kustomize
      - argocd
      - kubeseal
  become: yes

- aur:
    use: yay
    state: present
    name:
      - aws-iam-authenticator-bin
      - kubelogin
      - vcluster-bin
      - velero-bin
      - flux-bin

- name: Install crossplane cli
  shell: curl -sL https://raw.githubusercontent.com/crossplane/crossplane/release-1.5/install.sh | sh

# sudo mv kubectl-crossplane /usr/bin