---
- name: Enable multilib
  shell: sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
  args:
    warn: false
  become: yes

- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
  become: yes

- name: Install pacman apps
  pacman:
    state: present
    name:
      - chromium
      - copyq
      - dbeaver
      - discord
      - firefox
      - flameshot
      - kitty
      - peek
      - piper
      - steam
      - transmission-gtk
      - virtualbox
      - emacs
  become: yes

- aur:
    use: yay
    state: present
    name:
      - dropbox
      - insomnia-bin
      - slack-desktop
      - spotify
      - teams
      - timeshift
      - visual-studio-code-bin
