---
- name: Install Docker
  pacman:
    state: present
    name:
      - docker
      - docker-compose
  become: yes

- name: Enable and start docker service
  systemd:
    name: docker.service
    enabled: yes
    state: started
  become: yes

- name: Add the user to docker group
  user:
    name: "{{ ansible_user_id }}"
    group: docker
  become: yes
